"""Typed API for the Linux cgroup v2 extension.

Every reader method opens a fresh interface. Results from separate methods
are not an atomic snapshot. ``MaxOr[T]`` keeps the kernel's ``max`` distinct
from a concrete value; limits do not include ancestor limits or CPU affinity.
"""

from collections.abc import Mapping
from os import PathLike
from pathlib import Path
from typing import Generic, Literal, TypeAlias, TypeVar

PathArg: TypeAlias = str | bytes | PathLike[str] | PathLike[bytes]
CgroupKind: TypeAlias = Literal[
  "domain", "domain threaded", "domain invalid", "threaded"
]
_ValueT = TypeVar("_ValueT", int, float)

class MaxOr(Generic[_ValueT]):
  @property
  def is_max(self) -> bool: ...
  @property
  def value(self) -> _ValueT:
    """Concrete value, raising ValueError when is_max is true."""

class SakaiError(Exception): ...

class InterfaceMissingError(SakaiError):
  path: Path

class NotCgroupV2Error(SakaiError): ...

class DeletedCgroupError(SakaiError):
  path: Path

class CgroupParseError(SakaiError):
  path: Path

class NotSupportedError(SakaiError): ...

class Cgroup:
  @staticmethod
  def current() -> Cgroup: ...
  @staticmethod
  def from_pid(pid: int) -> Cgroup: ...
  @staticmethod
  def from_path(path: PathArg) -> Cgroup: ...
  @property
  def path(self) -> Path: ...
  def child(self, name: PathArg) -> Cgroup: ...
  def children(self) -> list[Cgroup]: ...
  def cpu(self) -> CpuReader: ...
  def memory(self) -> MemoryReader: ...
  def core(self) -> CoreReader: ...

class CpuReader:
  def stat(self) -> CpuStat: ...
  def stat_local(self) -> CpuStatLocal: ...
  def max(self) -> CpuMax: ...
  def weight(self) -> CpuWeight: ...
  def weight_nice(self) -> int: ...
  def max_burst(self) -> int: ...
  def idle(self) -> bool: ...
  def uclamp_min(self) -> float: ...
  def uclamp_max(self) -> MaxOr[float]: ...
  def pressure(self) -> Pressure: ...

class CpuStat:
  @property
  def time(self) -> CpuTimeStat: ...
  @property
  def bandwidth(self) -> CpuBandwidthStat | None: ...

class CpuStatLocal:
  @property
  def throttled_ns(self) -> int | None: ...

class CpuTimeStat:
  @property
  def usage_ns(self) -> int: ...
  @property
  def user_ns(self) -> int: ...
  @property
  def system_ns(self) -> int: ...

class CpuBandwidthStat:
  @property
  def nr_periods(self) -> int: ...
  @property
  def nr_throttled(self) -> int: ...
  @property
  def throttled_ns(self) -> int: ...
  @property
  def burst(self) -> CpuBurstStat | None: ...

class CpuBurstStat:
  @property
  def nr_bursts(self) -> int: ...
  @property
  def burst_ns(self) -> int: ...

class CpuMax:
  @property
  def quota_ns(self) -> MaxOr[int]: ...
  @property
  def period_ns(self) -> int: ...
  @property
  def cpu_count(self) -> MaxOr[float]: ...

class CpuWeight:
  @property
  def is_idle(self) -> bool: ...
  @property
  def shares(self) -> int | None: ...

class Pressure:
  @property
  def some(self) -> PressureLine: ...
  @property
  def full(self) -> PressureLine | None: ...

class PressureLine:
  @property
  def avg10(self) -> float: ...
  @property
  def avg60(self) -> float: ...
  @property
  def avg300(self) -> float: ...
  @property
  def total_ns(self) -> int: ...

class MemoryReader:
  def current(self) -> int: ...
  def peak(self) -> int: ...
  def max(self) -> MaxOr[int]: ...
  def high(self) -> MaxOr[int]: ...
  def low(self) -> int: ...
  def min(self) -> int: ...
  def stat(self) -> MemoryStat: ...
  def pressure(self) -> Pressure: ...

class MemoryStat:
  @property
  def bytes(self) -> Mapping[str, int]: ...
  @property
  def pages(self) -> Mapping[str, int]: ...
  @property
  def counts(self) -> Mapping[str, int]: ...

class CoreReader:
  def kind(self) -> CgroupKind: ...
  def controllers(self) -> list[str]: ...
  def subtree_control(self) -> list[str]: ...
